export const CHECK_TOKEN = "CHECK_TOKEN";
export const FETCH_TOKEN = "FETCH_TOKEN";
export const RESOLVE_TOKEN = "RESOLVE_TOKEN";
export const REQUEST_PROFILELIST = "REQUEST_PROFILELIST";
export const RECEIVE_PROFILELIST = "RECEIVE_PROFILELIST";